name: semgrep

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep scan
        run: semgrep --config "p/typescript" --sarif -o semgrep.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
